In [2]:
import nltk
import numpy as np 
import pandas as pd 
import seaborn as sns
import json
import tensorflow as tf
import tensorflow_text as tf_text


In [73]:
with open("E:/MLCourse/TF2/Notebook/SmartFennec/text\MathSentences.json",encoding="utf-8") as f:
    data=json.load(f)
wikidata=data["sentences"]

In [17]:
with open ("E:/MLCourse/TF2/Notebook/tutorialNotebook/data (1).json","r",encoding="utf-8") as f:
    message=json.load(f)
MessageKeys=list(message.keys())
queslist=[]
anslist=[]
messageData=[]
for eachkey in MessageKeys:
    for question in message[eachkey]["câu hỏi"]:
        queslist.append(question)
    for answer in message[eachkey]["trả lời"]:
        anslist.append(answer)
for i,j in zip(queslist,anslist):
    messageData.append(i+" "+j)

In [77]:
bigdata=messageData+wikidata

5980

In [78]:
with open("E:/MLCourse/TF2/Notebook/SmartFennec/bi_grams.txt",encoding="utf-8") as f:
    bi_gramtxt=f.read()
bi_gram_list=[]
for each in bi_gramtxt.split(","):
    each=each[:-1]
    each=each[2:]
    bi_gram_list.append(each)

In [3]:
basicTokenizer=tf_text.WhitespaceTokenizer()

In [62]:
# # Check if already in bigramdict
# def fit_on_text(text,dict):
#     d_continue=False
#     sth=[]
#     for i in range(0,len(text)):
#         if d_continue==True:
#             d_continue=False
#             continue
#         try:
#             pairtext=text[i]+" "+text[i+1]
#         except:
#             pairtext=""
#         # if i!=len(textlist):
#         #     pairtext=textlist[i]+" "+textlist[i+1]
#         for j in dict:
#             if pairtext.lower()==j:
#                 sth.append(dict[j])
#                 d_continue=True
#                 break
#         if d_continue==False:
#             for count,j in enumerate(dict):
#                 if text[i].lower()==j:
#                     sth.append(dict[j])
#                     break
#                 if count==len(dict)-1:
#                     sth.append(0)
#     return sth
#Pad sequence
def pad_sequence(datasequence):
    maxsen=0
    for i in datasequence:
        if maxsen<len(i):
            maxsen=len(i)

    for i in datasequence:
        while len(i)!=maxsen:
            i.insert(0,0)
    return np.array(dataseq)
#seq_to_word

# def seq_to_word(data):
#     tokens=[]
#     for eachpattern in data:
#         for eachword in eachpattern.split():
#             tokens.append(eachword.lower())
#     bi_grams=tf_text.ngrams(tokens,2,reduction_type=tf_text.Reduction.STRING_JOIN,string_separator=' ')
#     bg=np.array(bi_grams)
#     listwordbg=[]
#     # for i in bigramstring.split():
#     #     listwordbg.append(i)
#     listword=[]
#     for i in bg:
#         listword.append(i.decode("utf-8"))
#     chosenwords=[]
#     finaltokens=[]
#         # single word
#     for i in tokens:
#         check=True
#         for j in listwordbg:
#             if i==j:
#                 check=False
#                 break
#         if (finaltokens.count(i)==0) and (i!="?") and (i!="thế") and (i!="vậy") and (i!="nè") and (check):
#             finaltokens.append(i)
#         # bigram
#     for i in listword:
#         for j in bi_gram_list:
#             if (i==j) and (chosenwords.count(i)==0):
#                 chosenwords.append(i)
#     wordlist=finaltokens+chosenwords
#     print(chosenwords)
#     dict={}
#     for word in wordlist:
#         for stopword in stopwords:
#             if (word==stopword):
#                 wordlist.remove(word)
#     for i,j in enumerate(wordlist):
#         dict[j]=i+1
#         if j=="":
#             continue
#     return dict

In [55]:
def bi_gram_checker(bi_gram_word):
    for i in bi_gram_list:
        if (bi_gram_word==i):
            return True
    return False

def seq2word(data):
    word_to_index={}
    index_to_word={}
    myContinue=False
    tokens=[]
    for eachseq in data:
        listtokens=eachseq.lower().split(" ")
        listtokens.append("")
        for i in range(0,len(listtokens)-1):
            if (myContinue):
                myContinue=False
                continue
            if (listtokens[i+1]!=""):
                pairtext=listtokens[i]+" "+listtokens[i+1]
                if (bi_gram_checker(pairtext)):
                    myContinue=True
                    if (tokens.count(pairtext)==0):
                        tokens.append(pairtext)
            if (myContinue==False):  
                if (tokens.count(listtokens[i])==0):
                    tokens.append(listtokens[i])
    for index,word in enumerate(tokens):
        word_to_index[word]=index+1
        index_to_word[index+1]=word
    return word_to_index,index_to_word

def fitontext(textdata,dict):
    d_continue=False
    output=[]
    for text in textdata:
        text=text.lower().split(" ")
        text.append("")
        sth=[]
        for i in range(0,len(text)-1):
            if d_continue==True:
                d_continue=False
                continue
            if (text[i+1]!=""):
                pairtext=text[i]+" "+text[i+1]
            for j in dict:
                if pairtext.lower()==j:
                    sth.append(dict[j])
                    d_continue=True
                    break
            if d_continue==False:
                for count,j in enumerate(dict):
                    if text[i].lower()==j:
                        sth.append(dict[j])
                        break
                    if count==len(dict)-1:
                        sth.append(0)
        output.append(sth)
    return output

In [79]:
worddict,indexofword=seq2word(bigdata)
len(worddict)
dataseq=fitontext(bigdata,worddict)

In [49]:
# dataseq=[]
# basicTokenizer=tf_text.WhitespaceTokenizer()
# for eachseq in data["sentences"]:
#     tokenstext=np.array(basicTokenizer.tokenize(eachseq))
#     textlistt=[]
#     for i in tokenstext:
#         if (i.decode("utf-8")!="?") and (i.decode("utf-8")!="thế") and (i.decode("utf-8")!="vậy") and (i.decode("utf-8")!="nè") and (i.decode("utf-8")!="quá đi") and (i.decode("utf-8")!="vậy đi") and (i.decode("utf-8")!="á") and (i.decode("utf-8")!="với"):
#             textlistt.append(i.decode("utf-8"))
#     # print(eachseq)
#     seqfit=fit_on_text(textlistt,worddict)
#     dataseq.append(seqfit)

In [80]:
seqX=pad_sequence(dataseq)
seqX


array([[   0,    0,    0, ...,    4,    5,    6],
       [   0,    0,    0, ...,   11,   12,   13],
       [   0,    0,    0, ...,   17,   18,   19],
       ...,
       [   0,    0,    0, ...,  369,  477,  477],
       [   0,    0,    0, ...,  369, 3411, 3411],
       [   0,    0,    0, ...,    0,    0, 3411]])

In [10]:
sampling_table=tf.keras.preprocessing.sequence.make_sampling_table(size=10)
sampling_table

array([0.00315225, 0.00315225, 0.00547597, 0.00741556, 0.00912817,
       0.01068435, 0.01212381, 0.01347162, 0.01474487, 0.0159558 ])

In [81]:
# Whole thing
def generate_training_data(sequences,window_size,num_ns,vocab_size,seed):
    targets,contexts,labels=[],[],[]
    sampling_table=tf.keras.preprocessing.sequence.make_sampling_table(size=vocab_size)
    for sequence in sequences:
        positive_skip_grams, _ = tf.keras.preprocessing.sequence.skipgrams(
            sequence,
            vocabulary_size=vocab_size,
            window_size=window_size,
            negative_samples=0)
        for target_word,context_word in positive_skip_grams:
            context_class=tf.expand_dims(tf.constant([context_word],dtype="int64"),1)
            negative_sampling_candidates,_,_=tf.random.log_uniform_candidate_sampler(
                true_classes=context_class,
                num_true=1,
                num_sampled=num_ns,
                unique=True,
                range_max=vocab_size,
                seed=seed,
                name="negative_sampling"
            )
            negative_sampling_candidates=tf.expand_dims(negative_sampling_candidates,1)
            context=tf.concat([context_class,negative_sampling_candidates],0)
            label=tf.constant([1]+[0]*num_ns,dtype="int64")
            targets.append(target_word)
            contexts.append(context)
            labels.append(label)
    return targets, contexts, labels

In [65]:
# # Create window
# window_size=2
# positive_skip_grams, _ = tf.keras.preprocessing.sequence.skipgrams(
#     seqX.tolist()[0],
#     vocabulary_size=len(worddict),
#     window_size=window_size,
#     negative_samples=0
# )
# print(len(positive_skip_grams))

18


In [13]:
# # Negative Sampling
# target_word, context_word=positive_skip_grams[6]
# num_ns=4
# SEED=42
# context_class=tf.reshape(tf.constant(context_word,dtype="int64"),(1,1))
# negative_sampling_candidates,_,_=tf.random.log_uniform_candidate_sampler(
#     true_classes=context_class,
#     num_true=1,
#     num_sampled=num_ns,
#     unique=True,
#     range_max=len(worddict),
#     seed=SEED,
#     name="negative_sampling"
# )

# negative_sampling_candidates

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 51,   9, 173,  21], dtype=int64)>

In [14]:
# negative_sampling_candidates=tf.expand_dims(negative_sampling_candidates,1)
# context=tf.concat([context_class,negative_sampling_candidates],0)
# label=tf.constant([1]+[0]*num_ns,dtype="int64")

# target=tf.squeeze(target_word)
# context=tf.squeeze(context)
# label=tf.squeeze(label)

In [82]:
targets,contexts,labels=generate_training_data(
    seqX,
    window_size=3,
    num_ns=4,
    vocab_size=len(worddict)+1,
    seed=42
)
num_ns=4

In [98]:
len(worddict)
len(labels)

451170

In [84]:
BATCH_SIZE = 500
BUFFER_SIZE = 10000
dataset = tf.data.Dataset.from_tensor_slices(((targets, contexts), labels))
dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

In [85]:
dataset = dataset.cache().prefetch(buffer_size=tf.data.AUTOTUNE)
print(dataset)

<PrefetchDataset shapes: (((500,), (500, 5, 1)), (500, 5)), types: ((tf.int32, tf.int64), tf.int64)>


In [86]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Dot, Embedding, Flatten

In [87]:
class Word2Vec(Model):
  def __init__(self, vocab_size, embedding_dim):
    super(Word2Vec, self).__init__()
    self.target_embedding = Embedding(vocab_size,
                                      embedding_dim,
                                      input_length=1,
                                      name="w2v_embedding")
    self.context_embedding = Embedding(vocab_size,
                                       embedding_dim,
                                       input_length=num_ns+1)
    self.dots = Dot(axes=(3, 2))
    self.flatten = Flatten()

  def call(self, pair):
    target, context = pair
    word_emb = self.target_embedding(target)
    context_emb = self.context_embedding(context)
    dots = self.dots([context_emb, word_emb])
    return self.flatten(dots)

In [92]:
seqX.shape

(5980, 118)

In [88]:
def custom_loss(x_logit, y_true):
      return tf.nn.sigmoid_cross_entropy_with_logits(logits=x_logit, labels=y_true)

In [89]:
embedding_dim = 128
word2vec = Word2Vec(len(worddict)+1, embedding_dim)
word2vec.compile(optimizer='adam',
                 loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
                 metrics=['accuracy'])

In [93]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="logs")

In [94]:
word2vec.fit(dataset, epochs=500, callbacks=[tensorboard_callback])

Epoch 1/500
902/902 [==============================] - 15s 14ms/step - loss: 0.9641 - accuracy: 0.6481
Epoch 2/500
902/902 [==============================] - 11s 12ms/step - loss: 0.7769 - accuracy: 0.6967
Epoch 3/500
902/902 [==============================] - 11s 12ms/step - loss: 0.7151 - accuracy: 0.7231
Epoch 4/500
902/902 [==============================] - 11s 12ms/step - loss: 0.6549 - accuracy: 0.7498
Epoch 5/500
902/902 [==============================] - 11s 12ms/step - loss: 0.5990 - accuracy: 0.7746
Epoch 6/500
902/902 [==============================] - 11s 12ms/step - loss: 0.5496 - accuracy: 0.7967
Epoch 7/500
902/902 [==============================] - 11s 12ms/step - loss: 0.5071 - accuracy: 0.8153
Epoch 8/500
902/902 [==============================] - 11s 12ms/step - loss: 0.4714 - accuracy: 0.8303
Epoch 9/500
902/902 [==============================] - 11s 12ms/step - loss: 0.4418 - accuracy: 0.8418
Epoch 10/500
902/902 [==============================] - 11s 12ms/step - l

In [130]:

vocab=list(worddict.keys())
vocab.insert(0,"<PAD>")
len(vocab)

5228

In [131]:
import io
import re
import string
weights = word2vec.get_layer('w2v_embedding').get_weights()[0]

out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(vocab):
  if index == 0:
    continue  # skip 0, it's padding.
  vec = weights[index]
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
  out_m.write(word + "\n")
out_v.close()
out_m.close()

In [100]:
weights.shape

(5228, 128)

In [146]:
vocab_weights={}
weightslist=weights.tolist()
for index,word in enumerate(vocab):
    if index==0:
        continue
    vocab_weights[word]=weightslist[index]

with open("E:/MLCourse/TF2/Notebook/tutorialNotebook/new_vocabs_weights.json","w",encoding="utf-8") as f:
    json.dump(vocab_weights,f)

In [64]:
vocab=list(worddict.keys())


In [65]:
weights = word2vec.get_layer('w2v_embedding').get_weights()[0]
weights[0]

array([ 0.02234798, -0.02036996,  0.0244733 , -0.006604  , -0.01843094,
       -0.00436572, -0.03649978,  0.04763223,  0.03983975,  0.01366086,
       -0.04861617,  0.0159493 ,  0.03891993,  0.01603014,  0.01695739,
        0.02715579,  0.01401539,  0.02352457, -0.03075529, -0.00376249,
        0.01570125, -0.03463662,  0.01790473,  0.0247595 , -0.04686971,
       -0.03932341, -0.02829659, -0.01633142,  0.0465782 , -0.04074208,
       -0.02168462,  0.03254963,  0.03429175, -0.02250403,  0.02632345,
       -0.04833278, -0.00497564,  0.0046381 , -0.03242748,  0.02242507,
       -0.00606018, -0.00605351, -0.04198269, -0.04717908, -0.00924442,
       -0.0255707 ,  0.0108913 ,  0.04028672, -0.03128753, -0.00847763,
        0.02337762,  0.04639346, -0.00500913,  0.04189097,  0.03297232,
       -0.04273205,  0.02790445, -0.04894259,  0.04627626,  0.01257626,
       -0.0080957 ,  0.02868903, -0.04154355,  0.04719685,  0.0476823 ,
        0.04542429, -0.00266172,  0.04211965,  0.01761994, -0.01

In [66]:
def cosine_simalarity(label,target):
    return np.dot(label,target)/(np.dot(np.linalg.norm(label),np.linalg.norm(target)))

In [81]:
chosenword=input()
if vocab.count(chosenword)>0:
    print(chosenword)
    for i,word in enumerate(vocab):
        if word==chosenword:
            chosenweight=weights[i]
    cosinelist={}
    for i,word in enumerate(vocab):
        if word!=chosenword:
            cosinelist[word]=cosine_simalarity(chosenweight,weights[i])
    import pandas as pd
    dataframe=pd.DataFrame({"Words":cosinelist.keys(),"Similarity":cosinelist.values()})
    print(dataframe.sort_values(by=["Similarity"],ascending=False).head(10))
else:
    print("word not found")


đúc kết
           Words  Similarity
944    quy trình    0.857267
566        chỉnh    0.792563
943      quá khứ    0.754430
968      số phức    0.675230
942  kinh nghiệm    0.674900
766     những ai    0.672484
859      nhu cầu    0.658019
932    lập trình    0.646847
438         phức    0.639821
668     ứng dụng    0.628425
